### ISSUE TITLE
Not respond J-Link debug

### ISSUE THREAD

**Issue by arno608rw** [Decawave/mynewt-dw1000-apps#1]
![screen shot 2561-10-01 at 15 17 05](https://user-images.githubusercontent.com/3774145/46277401-3ed4e380-c58d-11e8-925f-e6d290630d5a.png)
![screen shot 2561-10-01 at 15 17 21](https://user-images.githubusercontent.com/3774145/46277406-41373d80-c58d-11e8-997d-e84c43e7dbc1.png)

**Comment by pkettle** [comment]
There where some recent changes made to mynewt_dw1000_core that are not reflected in all the mynewt_dw1000_apps. I believe this issue is related to the 8MHz SPI changes. Can you delete the following lines from twr_node_range:main.c:289-290 and twr_tag_range:main.c:179-180.

    dw1000_softreset(inst);
    dw1000_phy_init(inst, NULL);

**Comment by arno608rw** [comment]
![screen shot 2561-10-02 at 09 34 25](https://user-images.githubusercontent.com/3774145/46326319-61ffa180-c626-11e8-8d74-cdbf52284aa3.png)
![screen shot 2561-10-02 at 09 36 14](https://user-images.githubusercontent.com/3774145/46326391-a8550080-c626-11e8-8f29-46071672991b.png)

![screen shot 2561-10-02 at 09 35 04](https://user-images.githubusercontent.com/3774145/46326335-793e8f00-c626-11e8-80f5-56289b5023ab.png)

Not respond.. all example apps. What do I do wrong? Or do I skip that step?

**Comment by pkettle** [comment]
This response is correct. Can you confirm that the twr_node/tag example is working for you?

**Comment by arno608rw** [comment]
No working it same

**Comment by pkettle** [comment]
Can you confirm that you are using:
newt version
Apache Newt version: 1.4.1

**Comment by arno608rw** [comment]
![screen shot 2561-10-03 at 10 07 43](https://user-images.githubusercontent.com/3774145/46388048-3a770a80-c6f4-11e8-9cec-bb76e5b5ef7a.png)
Apache Newt version: 1.4.1

**Comment by pkettle** [comment]
Hi Arno, 
Everything looks fine. What I can conclude is that the tools are communicating with the target correctly. It appears that the node is waiting for a range_request from the tag and vice-versa. Can you confirm that one DeviceID = 0x1234 and the other DeviceID = 0x4321 for the twr_node/tag example.

Can you send me the output of: 
cd ./mynewt-dw1000-apps/repos/apache-mynewt-core
git log

**Comment by arno608rw** [comment]
I confirm DeviceID
node
![screen shot 2561-10-03 at 15 39 57](https://user-images.githubusercontent.com/3774145/46399688-a96b5800-c722-11e8-8463-963905522587.png)
tag
![screen shot 2561-10-03 at 15 39 51](https://user-images.githubusercontent.com/3774145/46399847-1bdc3800-c723-11e8-8e29-1ca789f018ef.png)

git log file
[Terminal Saved Output.txt](https://github.com/Decawave/mynewt-dw1000-apps/files/2441292/Terminal.Saved.Output.txt)

**Comment by pkettle** [comment]
Arno, 
Can you confirm are at the head of both repos:


```
cd ./mynewt-dw1000-apps
git log -1
commit 047ba114ae0f59907bec3aaa2a5da9f1dad5a0e0

cd ./mynewt-dw1000-apps/repos/mynewt-dw1000-core
git log -1
commit fbe15af4416ec373966959bca08a2b6189ecd051
```

**When you run:
newt run twr_node 0
Do you see the following on the RTT console?**

```
nc localhost 19021
SEGGER J-Link V6.30f - Real time terminal output
J-Link OB-STM32F072-128KB-CortexM compiled May  4 2017 14:43:23 V1.0, SN=760026028
Process: JLinkGDBServerCLExe

{"utime": 2557797,"timer_ev_cb":"rx_timeout_error"}
{"utime": 2573421,"timer_ev_cb":"rx_timeout_error"}
{"utime": 2589045,"timer_ev_cb":"rx_timeout_error"}
{"utime": 2604669,"timer_ev_cb":"rx_timeout_error"}
{"utime": 2620294,"timer_ev_cb":"rx_timeout_error"}
```


**With the twr_node running on one board run the tag example:
newt run twr_tag 0
You should see the following on the RTT console?**

```
nc localhost 19021
SEGGER J-Link V6.30f - Real time terminal output
J-Link OB-STM32F072-128KB-CortexM compiled May  4 2017 14:43:23 V1.0, SN=760007957
Process: JLinkGDBServerCLExe

{"utime": 2434656,"tof": 0,"range": 0,"res_req":"3803D8D", "rec_tra":"3803EB6", "rssi": -86}
1st={
    fctrl:0x8841,
    seq_num:0x4E,
    PANID:0xDECA,
    dst_address:0x1234,
    src_address:0x4321,
    code:0x0006,
    reception_timestamp:0x398B9DD2,
    transmission_timestamp:0x3D0BDC42,
    request_timestamp:0x1A4C9E42,
    response_timestamp:0x1DCCDD2A
}
2nd={
    fctrl:0x8841,
    seq_num:0x4F,
    PANID:0xDECA,
    dst_address:0x1234,
    src_address:0x4321,
    code:0x0008,
    reception_timestamp:0x1DCCDD2A,
    transmission_timestamp:0x214D1C42,
    request_timestamp:0x3D0BDC42,
    response_timestamp:0x408C1A4A
}
```

**Note: it is not possible to run both examples at the same time on the same physical machine. The best approach is to run the twr_node from a battery while running/debugging the twr_tag example.**

**Comment by arno608rw** [comment]
![screen shot 2561-10-04 at 11 58 07](https://user-images.githubusercontent.com/3774145/46453647-cbb9b000-c7cc-11e8-8f3c-884faf718cef.png)
cd ./mynewt-dw1000-apps
git log -1
commit 047ba114ae0f59907bec3aaa2a5da9f1dad5a0e0 it same

cd ./mynewt-dw1000-apps/repos/mynewt-dw1000-core
git log -1
commit fbe15af4416ec373966959bca08a2b6189ecd051 it not same i have 8c56c4827eb776966872b49eed3dd26f826c3051

I update code on git and testing...

After update
![screen shot 2561-10-04 at 12 10 59](https://user-images.githubusercontent.com/3774145/46454047-a29a1f00-c7ce-11e8-854d-b28f6a62e609.png)

And see the following on the RTT console in newt run twr_node 0 and newt run twr_tag and i use 2 pc (Macbook and iMac). it not work. hahahaha!!!!!

> nc localhost 19021
SEGGER J-Link V6.32h - Real time terminal output
J-Link OB-STM32F072-128KB-CortexM compiled May  4 2017 14:43:23 V1.0, SN=760038499
Process: JLinkGDBServerCLExe
device_id = 0xDECA0130
PANID = 0xDECA
DeviceID = 0x1234
partID = 0xD4009731
lotID = 0x4325100
xtal_trim = 0x15
frame_duration = 190 usec
holdoff = 896 usec

I can not git pull commit fbe15af4416ec373966959bca08a2b6189ecd051 ./mynewt-dw1000-apps/repos/mynewt-dw1000-core
> git pull fbe15af4416ec373966959bca08a2b6189ecd051
fatal: 'fbe15af4416ec373966959bca08a2b6189ecd051' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights

**Comment by pkettle** [comment]
Arno, 
The good news is, I was able to reproduce what you are seeing and have committed the necessary changes. 

`git pull on ./mynewt-dw1000-apps/repos/mynewt-dw1000-core `

You should be now at commit dba90f30149a794a5a26e87e97e8f1d9647fe4fa

**Comment by pkettle** [comment]
Hi Arno, 
Did this resolved your issue?
