### ISSUE TITLE
About the performance of WCS

### ISSUE THREAD

**Issue by ftianf** [Decawave/mynewt-dw1000-apps#10]
Hi, 

I noticed that in README.md of mynewt-timescale-lib, the performance of 1s CCP is ~500ps.
Got a few questions regarding the performance of CCP/WCS
- How is this measured? Is there a way to repeat the Benchmark test in one of the apps?
- If we change the profile to <1s CCP superframe, will this improve the 500ps skew?
- Is it possible to share the source codes of timescale-lib?

Regards
Feng

**Comment by pkettle** [comment]
Hi Feng, 
Have a look at the https://github.com/Decawave/mynewt-dw1000-apps/blob/bottleneck/apps/matlab/wcs_stats.m. This is a Matlab script that I use to study the WCS performance. In principle < 1s CCP should improve performance but we have not validated this. The timescale algorithm compensates for skew and drift (rate of change of skew). We are not planning on open sourcing the timescale-lib at this time.

**Comment by ftianf** [comment]
Thanks for answering my question. It's clear now.
