### ISSUE TITLE
newt install error

### ISSUE THREAD

**Issue by Robbinaa** [Decawave/mynewt-dw1000-apps#13]
Hi,
When I input a "newt install" order,once mynet-core download completed,error reports:
Error: Error downloading repository apache-mynewt-core: No remote upstream for branch "master".How could I deal with it?
Thanks.

**Comment by pkettle** [comment]
Hi @Robbinaa, I am not able to reproduce what you are seeing. Can you describe your setup? Below is what I see:

`
git clone https://github.com/Decawave/mynewt-dw1000-apps.git
Cloning into 'mynewt-dw1000-apps'...
$ cd mynewt-dw1000-apps/
$ newt install
Downloading repository mynewt-core (commit: master) from https://github.com/apache/mynewt-core.git
Downloading repository mynewt-dw1000-core (commit: master) from https://github.com/decawave/mynewt-dw1000-core.git
Downloading repository mynewt-timescale-lib (commit: master) from https://github.com/decawave/mynewt-timescale-lib.git
Downloading repository mynewt-nimble (commit: master) from https://github.com/apache/mynewt-nimble.git
Downloading repository mcuboot (commit: master) from https://github.com/JuulLabs-OSS/mcuboot.git
Making the following changes to the project:
    install apache-mynewt-core (1.5.0)
    install apache-mynewt-nimble (1.0.0)
    install mynewt-dw1000-core (1.0.0)
    install mynewt-timescale-lib (1.0.0)
apache-mynewt-core successfully installed version 1.5.0
apache-mynewt-nimble successfully installed version 1.0.0
mynewt-dw1000-core successfully installed version 1.0.0
mynewt-timescale-lib successfully installed version 1.0.0

`

**Comment by Robbinaa** [comment]
Hi,pkettle,
I gave up the windows environment and now I make it work in ubuntu 18.04 environment.
But when I test twr_node_tdma and twr_tag_tdma projects on dwm1001-devs following along with the tutorial,I cant get any range information on the console of the node.I can only get the output of the tag as follow:
`...
{"utime": 109054033,"wcs": [4742219576912,344173065808,3669085425081,344173065808],"skew": 13745941364036075520}
{"utime": 110129497,"wcs": [4810939070032,412892558928,3737804759353,412892558928],"skew": 13745936153028067328}
{"utime": 111204939,"wcs": [4879658563152,481612052048,3806524093777,481612052048],"skew": 13745931077211914240}
{"utime": 112280397,"wcs": [4948378056272,550331545168,3875243428347,550331545168],"skew": 13745926163984285696}
{"utime": 113355861,"wcs": [5017097549392,619051038288,3943962763065,619051038288],"skew": 13745921300708720640}
{"utime": 114431302,"wcs": [5085817042512,687770531408,4012682097924,687770531408],"skew": 13745916562273992704}
{"utime": 115506755,"wcs": [5154536535632,756490024528,4081401432922,756490024528],"skew": 13745911918145568768}
{"utime": 116582216,"wcs": [5223256028752,825209517648,4150120768079,825209517648],"skew": 13745906986908123136}
...
`
Does this mean the ccp and synchronization failed?Can you give me some advice.
Thanks.

**Comment by pkettle** [comment]
Hi @Robbinaa,

Can you try using the following configuration for the tag? The JSON logging currently requires NODE_START_SLOT_ID=0.

`newt target amend tag syscfg=NRNG_NNODES=4:NRNG_NFRAMES=8:NODE_START_SLOT_ID=0:NODE_END_SLOT_ID=7`

**Comment by Robbinaa** [comment]
Hi,@pkettle  ,thanks for your reply,
I tried the way of amending target twr_tag_tdma's syscfg,but it didn't work.And I changed the target twr_node_tdma's syscfg,it didn't work too.The output of console never changed.
By the way ,I'm not using the nranges_tdma project.
Thanks.

**Comment by pkettle** [comment]
Hi @Robbinaa, 
Can you try running the listener app and see what packets are being transmitted along with WCS. You should see nrng request between the nodes every second, and nrng requests between your tag and nodes at 80Hz.

**Comment by pkettle** [comment]
Hi @Robbinaa, 
Can you also confirm that you are at @mynewt-dw1000-core commit_id 205db09 or later? There has been some recent change to the trunk of late. Tag 1_2_0 is the last stable release.

**Comment by Robbinaa** [comment]
Hi,@pkettle ,I confirmed the commit_id at @mynewt-dw1000-core is 205db09.And I got these msgs from the listener app:
![image](https://user-images.githubusercontent.com/50039338/57270157-c4d58180-70bc-11e9-8cf6-2dc235962eb7.png)
I can see nrng request between the nodes every second,and nrng requests between my tag and nodes at 40Hz.

**Comment by pkettle** [comment]
Hi Robbinaa, 
Ok, this suggests that everything is working and the problem is related to recent PAN updates. Can you confirm you rebuild the master_node for the @mynewt-dw1000-core commit_id 205db09? I suspect the problem is related to line https://github.com/Decawave/mynewt-dw1000-core/blob/523f138a69594b2023f072b41a56535f059299dc/lib/nrng/src/nrng_encode.c#L84.

**Comment by Robbinaa** [comment]
Hi,@pkettle ,This is what I get when I use a "grep -r 205db09 ~/mynewt-dw1000-apps/" command:
/home/zyk/mynewt-dw1000-apps/repos/mynewt-dw1000-core/.git/FETCH_HEAD:205db09e03cec3bf20db7a978c09014854c576a1		branch 'master' of https://github.com/decawave/mynewt-dw1000-core
/home/zyk/mynewt-dw1000-apps/repos/mynewt-dw1000-core/.git/packed-refs:205db09e03cec3bf20db7a978c09014854c576a1 refs/remotes/origin/master
/home/zyk/mynewt-dw1000-apps/bin/targets/twr_tag_tdma/app/apps/twr_tag_tdma/manifest.json:      "commit": "205db09e03cec3bf20db7a978c09014854c576a1",
/home/zyk/mynewt-dw1000-apps/bin/targets/twr_node_tdma/app/apps/twr_node_tdma/manifest.json:      "commit": "205db09e03cec3bf20db7a978c09014854c576a1",
/home/zyk/mynewt-dw1000-apps/bin/targets/master_node/app/apps/twr_node_nranges_tdma/manifest.json:      "commit": "205db09e03cec3bf20db7a978c09014854c576a1",
/home/zyk/mynewt-dw1000-apps/bin/targets/dwm1001_boot/app/apps/boot/manifest.json:      "commit": "205db09e03cec3bf20db7a978c09014854c576a1",
/home/zyk/mynewt-dw1000-apps/bin/targets/listener/app/apps/listener/manifest.json:      "commit": "205db09e03cec3bf20db7a978c09014854c576a1",
``

**Comment by pkettle** [comment]
Hi Robbinaa,
Can you 
```
cd ./repos/mynewt-dw1000-core
git log
```
You should be @ commit 460610f0f9d404761b5b3274f6d7fd187fd48684 or later
Author: Niklas Casaril <niklas@casaril.com>
Date:   Sat May 4 09:56:37 2019 +1000
    Changed slot_id numbering to start from zero instead of one

If not do 
`git pull` 
Then rebuild master_node, slave_node, and tag.

**Comment by Robbinaa** [comment]
Hi@pkettle ,I don't quite understand what 'commit 460610f' means.This is my version.
![image](https://user-images.githubusercontent.com/50039338/57306752-f595d500-7115-11e9-8e0c-6b8bb1920d83.png)
Should I have a "git pull"?
Maybe I need to reiterate that I'm just using twr_node_tdma ,not twr_node_nrange_tdma.

**Comment by pkettle** [comment]
Hi Robbinaa, 
You are at the head of the master, git pull not required. Did you rebuild all targets?

**Comment by Robbinaa** [comment]
Hi@pkettle，
I rebuilded all targets ,but for twr_node_tdma,it still didn't work. 
Now I find the target twr_node_nranges_tdma can work normally.
