### ISSUE TITLE
SlotIndex_mex undefined

### ISSUE THREAD

**Issue by Robbinaa** [Decawave/mynewt-dw1000-apps#14]
Hi@pkettle ,
I run 'nrange_stats.m' on matlab for testing twr_nranges_tdma,but got a error report that 
'SlotIndex_mex undefined'.And I can find the function 'SlotIndex_mex'.
Where can I find it?
thanks.

**Comment by pkettle** [comment]
Hi Robbinaa, 
I just push the missing files, you will need to run .matlab/bootstrap to generate the SlotIndex_mex file. The matlab scripts are constantly evolving as we debug different aspects of the stack so we may have to do some tweaking.
