### ISSUE TITLE
newt load command taking too much time

### ISSUE THREAD

**Issue by ghost** [Decawave/mynewt-dw1000-apps#16]
Hello,

I erased the default flash image using JLink. Now, while loading the bootloader as per gievn guideline on github, it is stuck at point . I have shown here the verbose that I got 👎

 newt load dwm1001_boot -v
Loading bootloader
Load command: E:/Projects/RTLS/nRF/GitCodes/mynewt-dw1000-apps/repos/mynewt-dw1000-core/hw/bsp/dwm1001/dwm1001_download.cmd E:/Projects/RTLS/nRF/GitCodes/mynewt-dw1000-apps/repos/mynewt-dw1000-core/hw/bsp/dwm1001 bin\targets\dwm1001_boot\app\apps\boot\boot
Environment:
* BOOT_LOADER=1
* FEATURES=BASELIBC_PRESENT BOOT_LOADER BSP_NRF52 CONSOLE_UART_BAUD CONSOLE_UART_DEV CONSOLE_UART_FLOW_CONTROL DW1000_DEVICE_0_IRQ DW1000_DEVICE_0_RST DW1000_DEVICE_0_RX_ANT_DLY DW1000_DEVICE_0_SS DW1000_DEVICE_0_TX_ANT_DLY DW1000_DEVICE_BAUDRATE_HIGH DW1000_DEVICE_BAUDRATE_LOW FLASH_MAP_MAX_AREAS HAL_FLASH_VERIFY_BUF_SZ I2C_0_FREQ_KHZ I2C_1_FREQ_KHZ I2C_1_PIN_SCL I2C_1_PIN_SDA MBEDTLS_AES_C MBEDTLS_BASE64_C MBEDTLS_ECP_DP_SECP224R1 MBEDTLS_ENTROPY_C MBEDTLS_PKCS1_V15 MBEDTLS_PKCS1_V21 MCU_DCDC_ENABLED MCU_FLASH_MIN_WRITE_SIZE MCU_NRF52832 MSYS_1_BLOCK_SIZE NFC_PINS_AS_GPIO OS_CPUTIME_FREQ OS_CTX_SW_STACK_GUARD OS_IDLE_TICKLESS_MS_MAX OS_IDLE_TICKLESS_MS_MIN OS_MAIN_STACK_SIZE OS_MAIN_TASK_PRIO OS_SYSVIEW_TRACE_CALLOUT OS_SYSVIEW_TRACE_EVENTQ OS_SYSVIEW_TRACE_MUTEX OS_SYSVIEW_TRACE_SEM QSPI_FLASH_SECTOR_COUNT QSPI_PIN_CS QSPI_PIN_DIO0 QSPI_PIN_DIO1 QSPI_PIN_DIO2 QSPI_PIN_DIO3 QSPI_PIN_SCK SANITY_INTERVAL SPI_0_MASTER_PIN_MISO SPI_0_MASTER_PIN_MOSI SPI_0_MASTER_PIN_SCK TIMER_0 UARTBB_0_PIN_RX UARTBB_0_PIN_TX UART_0_PIN_CTS UART_0_PIN_RTS UART_0_PIN_RX UART_0_PIN_TX UART_1_PIN_CTS UART_1_PIN_RTS WATCHDOG_INTERVAL XTAL_32768
* FLASH_OFFSET=0x0
* IMAGE_SLOT=0
* CORE_PATH=E:/Projects/RTLS/nRF/GitCodes/mynewt-dw1000-apps/repos/apache-mynewt-core
* BSP_PATH=E:/Projects/RTLS/nRF/GitCodes/mynewt-dw1000-apps/repos/mynewt-dw1000-core/hw/bsp/dwm1001
* BIN_BASENAME=bin\targets\dwm1001_boot\app\apps\boot\boot

After this, nothing is happening . How much time does it takes to upload the bootloader?

Thanks & Regards
Asmita

**Comment by pkettle** [comment]
Hi Asmita, 
Not sure what is going on here. Can you try using Ubuntu or OSX? This looks like a tools chain issue.

**Comment by ghost** [comment]
Hi pkettle
I tried on Ubuntu. I am getting error as :

asmita@asmita-Lenovo-G50-80:~/Desktop/Asmita/newtProjects/windows-build-newt/mynewt-dw1000-apps$ newt load dwm1001_boot
Loading bootloader
Error: fork/exec /home/asmita/Desktop/Asmita/newtProjects/windows-build-newt/mynewt-dw1000-apps/repos/mynewt-dw1000-core/hw/bsp/dwm1001/dwm1001_download.sh: permission denied

Kindly suggest.

Thanks & Regards
Asmita

**Comment by ghost** [comment]
newt load working on Ubuntu properly
Thanks

**Comment by ghost** [comment]
newt load working on Ubuntu properly
Thanks
