### ISSUE TITLE
Error in newt run twr_tag_tdma 0

### ISSUE THREAD

**Issue by ghost** [Decawave/mynewt-dw1000-apps#17]
Hello,
I am trying to flash DWM1001-dev kit with mynewt based firmware image as given on https://github.com/Decawave/mynewt-dw1000-apps.
I am successfully able to newt load boot image using Ubuntu16.04 but I am getting error at 

newt run twr_tag_tdma 0 

Error is:

Copying /home/asmita/Desktop/Asmita/newtProjects/mynewt-dw1000-apps/bin/targets/twr_tag_tdma/app/lib/timescale/timescale_m4_hardfloat/libtimescale_core.a
Error: repos/mynewt-dw1000-core/lib/pan/src/pan.c:129:5: error: initializer element is not constant
     .rx_timeout_period = MYNEWT_VAL(PAN_RX_TIMEOUT),        // Receive response timeout in usec.
     ^
repos/mynewt-dw1000-core/lib/pan/src/pan.c:129:5: error: (near initialization for 'g_config.rx_timeout_period')

Kindly suggest. It would be very helpful.

Thanks & Regards
Asmita

**Comment by pkettle** [comment]
Hi Asmita, 
Can you let me know what compiler version you are using?

Can you try making the following changes to ./lib/pan/syscfg.yml 

from:
PAN_RX_TIMEOUT:
        description: 'TOA timeout delay for PAN (usec)'
        value: ((uint16_t)0x0600)
to:
PAN_RX_TIMEOUT:
        description: 'TOA timeout delay for PAN (usec)'
        value: ((const uint16_t)0x0600)
or:
PAN_RX_TIMEOUT:
        description: 'TOA timeout delay for PAN (usec)'
        value: 0x0600UL

**Comment by ghost** [comment]
Hi pkettle
I tried both the ways but same error is coming.
I am using :

asmita@asmita-Lenovo-G50-80:~$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



asmita@asmita-Lenovo-G50-80:~$ arm-none-eabi-gdb --version
GNU gdb (7.10-1ubuntu3+9) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.


asmita@asmita-Lenovo-G50-80:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thanks & regards
Asmita

**Comment by pkettle** [comment]
Hi Asmita, 
For what it is worth, I am using:

arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Can you try changing: ./lib/pan/src/pan.c:127, 

from:
static dw1000_pan_config_t g_config = {
    .tx_holdoff_delay = MYNEWT_VAL(PAN_TX_HOLDOFF),         // Send Time delay in usec.
    .rx_timeout_period = MYNEWT_VAL(PAN_RX_TIMEOUT),        // Receive response timeout in usec.
    .lease_time = MYNEWT_VAL(PAN_LEASE_TIME)                // Lease time in seconds
};

to:
dw1000_pan_config_t g_config = {
    .tx_holdoff_delay = MYNEWT_VAL(PAN_TX_HOLDOFF),         // Send Time delay in usec.
    .rx_timeout_period = MYNEWT_VAL(PAN_RX_TIMEOUT),        // Receive response timeout in usec.
    .lease_time = MYNEWT_VAL(PAN_LEASE_TIME)                // Lease time in seconds
};

or:
static dw1000_pan_config_t g_config = {
    .tx_holdoff_delay = MYNEWT_VAL(PAN_TX_HOLDOFF),         // Send Time delay in usec.
    .rx_timeout_period = **(const uint32_t)**MYNEWT_VAL(PAN_RX_TIMEOUT),        // Receive response timeout 
    .lease_time = (const)MYNEWT_VAL(PAN_LEASE_TIME)                // Lease time in seconds
};

**Comment by pkettle** [comment]
Correction:
or:
static dw1000_pan_config_t g_config = {
.tx_holdoff_delay = MYNEWT_VAL(PAN_TX_HOLDOFF), // Send Time delay in usec.
.rx_timeout_period = (const uint32_t)MYNEWT_VAL(PAN_RX_TIMEOUT), // Receive response timeout
.lease_time = (const)MYNEWT_VAL(PAN_LEASE_TIME) // Lease time in seconds
};

**Comment by ghost** [comment]
Hello pkettle
Things are working fine with version 7 of toolchain.
Thanks

Regards
Asmita
