### ISSUE TITLE
ccp example

### ISSUE THREAD

**Issue by justinleeyang** [Decawave/mynewt-dw1000-apps#2]
what's problem  ccp example can slove ?

**Comment by pkettle** [comment]
Hi Justin,
Clock Calibration Packet (CCP) is very useful for synchronized networks;
CCP enables Time Division Multiple Access (TDMA). CCP enables Wireless Clock Synchronization (WCS). CCP/TDMA/WCS improves channel utilization. However, the decision to use the CCP really demands on your target application. What is your target application?
