### ISSUE TITLE
compile error  with twr_tag_tdma twr_node_tdma

### ISSUE THREAD

**Issue by horst-m** [Decawave/mynewt-dw1000-apps#20]
hello,
I followed the directions in the readme, but can not compile the examples.
I've read the previous issues and downgraded the toolchain to 7-2017-q4.
now the twr_nranges_tdma compiles and runs (I had that `error: initializer element is not constant` before), but the error in twr_tag_tdma and twr_node_tdma stayed.
the error message is:

`Error: apps/twr_tag_tdma/src/main.c: In function 'slot_cb':
apps/twr_tag_tdma/src/main.c:91:40: error: 'tdma_instance_t {aka struct _tdma_instance_t}' has no member named 'parent'
     dw1000_dev_instance_t * inst = tdma->parent;
                                        ^~
apps/twr_tag_tdma/src/main.c:95:13: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'pan'
     if (inst->pan->status.valid == false) return;
             ^~
apps/twr_tag_tdma/src/main.c:99:43: error: passing argument 1 of 'tdma_tx_slot_start' from incompatible pointer type [-Werror=incompatible-pointer-types]
     uint64_t dx_time = tdma_tx_slot_start(inst, idx) & 0xFFFFFFFFFE00UL;
                                           ^~~~
In file included from apps/twr_tag_tdma/src/main.c:46:0:
repos/mynewt-dw1000-core/lib/tdma/include/tdma/tdma.h:110:10: note: expected 'struct _tdma_instance_t *' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 uint64_t tdma_tx_slot_start(struct _tdma_instance_t * tdma, float idx);
          ^~~~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c:105:33: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'ccp'
     uint16_t node_address = inst->ccp->frames[0]->short_address;
                                 ^~
apps/twr_tag_tdma/src/main.c:106:39: error: passing argument 1 of 'dw1000_rng_request_delay_start' from incompatible pointer type [-Werror=incompatible-pointer-types]
     if(dw1000_rng_request_delay_start(inst, node_address, dx_time, DWT_SS_TWR).start_tx_error){
                                       ^~~~
In file included from apps/twr_tag_tdma/src/main.c:40:0:
repos/mynewt-dw1000-core/lib/rng/include/rng/rng.h:195:21: note: expected 'struct _dw1000_rng_instance_t *' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 dw1000_dev_status_t dw1000_rng_request_delay_start(struct _dw1000_rng_instance_t * rng, uint16_t dst_address, uint64_t delay, dw1000_rng_modes_t protocal);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c: In function 'complete_cb':
apps/twr_tag_tdma/src/main.c:161:39: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'rng'
     dw1000_rng_instance_t * rng = inst->rng;
                                       ^~
apps/twr_tag_tdma/src/main.c: In function 'slot_complete_cb':
apps/twr_tag_tdma/src/main.c:188:39: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'rng'
     dw1000_rng_instance_t * rng = inst->rng;
                                       ^~
apps/twr_tag_tdma/src/main.c: In function 'pan_slot_timer_cb':
apps/twr_tag_tdma/src/main.c:244:40: error: 'tdma_instance_t {aka struct _tdma_instance_t}' has no member named 'parent'
     dw1000_dev_instance_t * inst = tdma->parent;
                                        ^~
apps/twr_tag_tdma/src/main.c:247:13: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'pan'
     if (inst->pan->status.valid &&
             ^~
apps/twr_tag_tdma/src/main.c:248:36: error: passing argument 1 of 'dw1000_pan_lease_remaining' from incompatible pointer type [-Werror=incompatible-pointer-types]
         dw1000_pan_lease_remaining(inst)>MYNEWT_VAL(PAN_LEASE_EXP_MARGIN)) {
                                    ^~~~
In file included from apps/twr_tag_tdma/src/main.c:42:0:
repos/mynewt-dw1000-core/lib/pan/include/pan/pan.h:132:10: note: expected 'dw1000_pan_instance_t * {aka struct _dw1000_pan_instance_t *}' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 uint32_t dw1000_pan_lease_remaining(dw1000_pan_instance_t * pan);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c:254:57: error: passing argument 1 of 'tdma_rx_slot_start' from incompatible pointer type [-Werror=incompatible-pointer-types]
         dw1000_set_delay_start(inst, tdma_rx_slot_start(inst, idx));
                                                         ^~~~
In file included from apps/twr_tag_tdma/src/main.c:46:0:
repos/mynewt-dw1000-core/lib/tdma/include/tdma/tdma.h:111:10: note: expected 'struct _tdma_instance_t *' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 uint64_t tdma_rx_slot_start(struct _tdma_instance_t * tdma, float idx);
          ^~~~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c:256:27: error: passing argument 1 of 'dw1000_pan_listen' from incompatible pointer type [-Werror=incompatible-pointer-types]
         dw1000_pan_listen(inst, DWT_BLOCKING);
                           ^~~~
In file included from apps/twr_tag_tdma/src/main.c:42:0:
repos/mynewt-dw1000-core/lib/pan/include/pan/pan.h:129:21: note: expected 'dw1000_pan_instance_t * {aka struct _dw1000_pan_instance_t *}' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 dw1000_dev_status_t dw1000_pan_listen(dw1000_pan_instance_t * pan, dw1000_dev_modes_t mode);
                     ^~~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c:259:47: error: passing argument 1 of 'tdma_tx_slot_start' from incompatible pointer type [-Werror=incompatible-pointer-types]
         uint64_t dx_time = tdma_tx_slot_start(inst, idx + 1.0f/16);
                                               ^~~~
In file included from apps/twr_tag_tdma/src/main.c:46:0:
repos/mynewt-dw1000-core/lib/tdma/include/tdma/tdma.h:110:10: note: expected 'struct _tdma_instance_t *' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 uint64_t tdma_tx_slot_start(struct _tdma_instance_t * tdma, float idx);
          ^~~~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c:260:26: error: passing argument 1 of 'dw1000_pan_blink' from incompatible pointer type [-Werror=incompatible-pointer-types]
         dw1000_pan_blink(inst, 2, DWT_BLOCKING, dx_time);
                          ^~~~
In file included from apps/twr_tag_tdma/src/main.c:42:0:
repos/mynewt-dw1000-core/lib/pan/include/pan/pan.h:130:21: note: expected 'dw1000_pan_instance_t * {aka struct _dw1000_pan_instance_t *}' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 dw1000_pan_status_t dw1000_pan_blink(dw1000_pan_instance_t * pan, uint16_t role, dw1000_dev_modes_t mode, uint64_t delay);
                     ^~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c: In function 'main':
apps/twr_tag_tdma/src/main.c:315:22: error: passing argument 1 of 'dw1000_ccp_start' from incompatible pointer type [-Werror=incompatible-pointer-types]
     dw1000_ccp_start(inst, CCP_ROLE_SLAVE);
                      ^~~~
In file included from repos/mynewt-dw1000-core/lib/tdma/include/tdma/tdma.h:46:0,
                 from apps/twr_tag_tdma/src/main.c:46:
repos/mynewt-dw1000-core/lib/ccp/include/ccp/ccp.h:190:6: note: expected 'dw1000_ccp_instance_t * {aka struct _dw1000_ccp_instance_t *}' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 void dw1000_ccp_start(dw1000_ccp_instance_t *ccp, dw1000_ccp_role_t role);
      ^~~~~~~~~~~~~~~~
apps/twr_tag_tdma/src/main.c:320:22: error: passing argument 1 of 'dw1000_pan_start' from incompatible pointer type [-Werror=incompatible-pointer-types]
     dw1000_pan_start(inst, PAN_ROLE_SLAVE);
                      ^~~~
In file included from apps/twr_tag_tdma/src/main.c:42:0:
repos/mynewt-dw1000-core/lib/pan/include/pan/pan.h:128:6: note: expected 'dw1000_pan_instance_t * {aka struct _dw1000_pan_instance_t *}' but argument is of type 'dw1000_dev_instance_t * {aka struct _dw1000_dev_instance_t *}'
 void dw1000_pan_start(dw1000_pan_instance_t * pan, dw1000_pan_role_t role);
      ^~~~~~~~~~~~~~~~
In file included from apps/twr_tag_tdma/src/main.c:35:0:
apps/twr_tag_tdma/src/main.c:333:116: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'rng'
     printf("{\"utime\": %lu,\"msg\": \"holdoff = %d usec\"}\n",utime,(uint16_t)ceilf(dw1000_dwt_usecs_to_usecs(inst->rng->config.tx_holdoff_delay)));
                                                                                                                    ^
repos/mynewt-dw1000-core/hw/drivers/dw1000/include/dw1000/dw1000_dev.h:359:50: note: in definition of macro 'dw1000_dwt_usecs_to_usecs'
 #define dw1000_dwt_usecs_to_usecs(_t) (double)( (_t) * (0x10000UL/(128*499.2)))
                                                  ^~
apps/twr_tag_tdma/src/main.c:358:26: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'tdma'
     tdma_assign_slot(inst->tdma, slot0_cb, g_slot[0], &g_slot[0]);
                          ^~
apps/twr_tag_tdma/src/main.c:359:26: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'tdma'
     tdma_assign_slot(inst->tdma, pan_slot_timer_cb, g_slot[1], &g_slot[1]);
                          ^~
apps/twr_tag_tdma/src/main.c:362:30: error: 'dw1000_dev_instance_t {aka struct _dw1000_dev_instance_t}' has no member named 'tdma'
         tdma_assign_slot(inst->tdma, slot_cb, g_slot[i], &g_slot[i]);
                              ^~
cc1: all warnings being treated as errors

`
starting at the top with: `'tdma_instance_t {aka struct _tdma_instance_t}' has no member named 'parent'`
 I had a quick look in repos/mynewt-dw100-core/lib/tdma/tdma.h 
and found: the compiler is right, as far as i see. 
I checked for other header-files with a different definition, but found none. 

I found in the changes of mynewt-dw1000-core a week ago in lib/survey/src/survey.c  
  the similar line (244)
  `dw1000_dev_instance_t * inst = tdma->parent;` 
was changed to:
   `dw1000_dev_instance_t * inst = tdma->dev_inst;`

so now I'm unshure, whether the problem is me, my setup or something in the code...
any suggestions are welcome,

regards horst

**Comment by horst-m** [comment]
I see there has been a lot of commitment by @ncasaril around the tdma.h and in the core in the last month, so I figure the changes have not yet found their way into each and every app.
actually I think work on the code is pretty cool, but a note, that the getting started example in the readme is not functional at the moment, would help people like me... :o)
regards horst

**Comment by ncasaril** [comment]
Very fair comment. I've been working through a bigger consolidation and seem to have missed updating the app in question. 

Can you have a look at the twr_nranges_tdma in the meantime? That one is hopefully up to date. 

I'll get through the other apps in the coming days.

**Comment by horst-m** [comment]
i do that, thanx for the answer!

**Comment by horst-m** [comment]
:-)
