### ISSUE TITLE
openThreadApp not working

### ISSUE THREAD

**Issue by shivmohith** [Decawave/mynewt-dw1000-apps#23]
Hi 
I was trying to work with the openThreadApp, followed the steps properly, faced no issues until I had to run the 'newt build openThreadApp'- several errors started to appear one after the other, tried to resolve a few but wasn't enough.
I have observed that there have been recent changes in both the dwm100-core and apps repository.
Is there anything I can try to solve this issue

**Comment by ncasaril** [comment]
Hi,
I've got it building but there's something going on under the surface that I'm not entirely across. 
I'm waiting for assistance from the people who implemented it. 
Thanks for your patience :) 
/N

**Comment by ncasaril** [comment]
I've merged the openTheadApp to master now and updated it to work with the current https://github.com/Decawave/mynewt-dw1000-core
Let me know if this fixes your issue @Shivmohith
