### ISSUE TITLE
build errors  while building tag_mesh

### ISSUE THREAD

**Issue by Manoj041** [Decawave/mynewt-dw1000-apps#31]
hi @ncasaril 
i am trying to build tag_mesh tapp,i am getting following build errors.
```

Error: repos/apache-mynewt-nimble/nimble/host/src/ble_sm.c: In function 'ble_sm_key_exch_exec':
repos/apache-mynewt-nimble/nimble/host/src/ble_sm.c:2054:30: error: taking address of packed member of 'struct ble_sm_master_id' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 2054 |         rc = ble_sm_gen_ediv(&master_id->ediv);
      |                              ^~~~~~~~~~~~~~~~
repos/apache-mynewt-nimble/nimble/host/src/ble_sm.c:2059:40: error: taking address of packed member of 'struct ble_sm_master_id' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 2059 |         rc = ble_sm_gen_master_id_rand(&master_id->rand_val);
      |                                        ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
can you please help me solving this issue.

thanks
manoj

**Comment by ncasaril** [comment]
Hi Manoj,

It looks like this is a problem in nimble rather than in mynewt-dw1000-core / apps.
Can you have a look at what version of mynewt and nimble you're using. I.e. run 
```
newt info
``` 

You should be using the versions supported in repository.yml. That is, the compatible versions should be installed if you run:

```
newt upgrade
```

Kind regards,
Niklas

**Comment by Manoj041** [comment]
hi Niklas,
already i done  newt upgrade but still i am facing same issue.```

newt info:
Apache Newt 1.8.0 / ab96a8a / 2020-03-18_18:42
Repository info:
    * apache-mynewt-core: e311e78e59e71aae72679b76baea8fd9e2aa18e8, 1.5.0
    * apache-mynewt-mcumgr: 40341abeeac9c93b4aa59c20ee183376c7920d7e
    * apache-mynewt-nimble: a85b65d97ecd062d8ea88c1a151f649e35e47420, 1.0.0
    * mcuboot: 377307de7dd0330dda289293cb26978b660a4f95, (dirty: local changes)
    * mynewt-dw1000-apps (project): b2768e3b18417849be385bb1d422a3eb8c58cc61
    * mynewt-dw1000-core: d6b1414f1b4527abda7521a304baa1c648244108, 0.0.0
    * mynewt-timescale-lib: 948eab9c5fdd8edfa53aa12f0dd7aada6e379c83, 1.0.1
```
thanks
manoj
