### ISSUE TITLE
twr_tag_tdma_ota_ble  build error

### ISSUE THREAD

**Issue by justinleeyang** [Decawave/mynewt-dw1000-apps#4]
hi,
I try the example twr_tag_tdma_ota_ble, when build error, the information as following：

> justinlee@justinlee:~/mynewt/mynewt-dw1000-apps$ newt build tag
> Warning: Package "/home/justinlee/mynewt/mynewt-dw1000-apps/apps/depreciated/lwip_p2p_rx" > > has incorrect "pkg.name" field in its `pkg.yml` file (pkg.name=apps/lwip_p2p_rx); ignoring package.
> Warning: Package "/home/justinlee/mynewt/mynewt-dw1000-apps/apps/depreciated/lwip_p2p_tx" > > has incorrect "pkg.name" field in its `pkg.yml` file (pkg.name=apps/lwip_p2p_tx); ignoring package.
> Building target targets/tag
> Error: Unsatisfied APIs detected:
>     ble_transport, required by: nimble/host
>

**Comment by pkettle** [comment]
Hi Justin,
I saw the same, this has been resolved in the refactor branch and will be merged with master this week.
