### ISSUE TITLE
Example listener missing _dw1000_cir_complex

### ISSUE THREAD

**Issue by michist** [Decawave/mynewt-dw1000-apps#5]
For the listener example the definition of _dw1000_cir_complex is missing
`
Error: apps/listener/src/main.c: In function 'process_rx_data_queue':
apps/listener/src/main.c:193:17: error: invalid use of undefined type 'struct _dw1000_cir_complex'
                 printf("%c%d", (i==0)? '[':',', cirp[i].real);
`

**Comment by pkettle** [comment]
Hi Michist, 

This issue has been resolved in the bottleneck branch and will be merged into the master shortly.
