### ISSUE TITLE
Up to now do the CCP/TDMA/WCS work well?

### ISSUE THREAD

**Issue by killeder** [Decawave/mynewt-dw1000-apps#6]
Up to now do the CCP/TDMA/WCS work well? And how many tdma slots in one superframe?

**Comment by pkettle** [comment]
Hi Killeder,
There are 160 slots to each superframe, this is not a hard limit but an imposed limit set by the nrng use case. The nrng use case is to range to 16 anchors in a single slot (currently we are at 12). The WCS transforms all stamps to the master reference frame. This has been working well, are you seeing a problem?

**Comment by killeder** [comment]
thank for your timely answer,i am just a beginner.
