### ISSUE TITLE
Newt issue

### ISSUE THREAD

**Issue by Vilucas** [Decawave/mynewt-dw1000-apps#7]
Hi,

I'm trying to do the first step to compile some projects with newt but I get the folowing error 

![newt](https://user-images.githubusercontent.com/42494104/52576064-b4946a00-2e1f-11e9-823a-95bb16f94e12.PNG)

I'm on windows, do you have any idea of what could be the reason ?

thx in advance,
Vilucas

**Comment by pkettle** [comment]
Hi Vilucas, 
It appears you do not have the  mynewt-dw1000-core repo installed. Did you do a newt install?

```
cd ./mynewt_dw1000_apps
newt install
cd ./apps
```

The mynewt-dw1000-core contains the BSP, and this is a dependent repo that is checkout with the newt install command. If successful you should have a directory ./mynewt-dw1000-apps/repos/mynewt-dw1000-core.

**Comment by Vilucas** [comment]
Thanks a lot for your quick answer. 

It is now working, but I have a last (I hope) issue on flashing the device on my dw1001-dev board, indeed I'm stuck on the last cmd 

![newt2](https://user-images.githubusercontent.com/42494104/52639619-f29f9580-2ed4-11e9-93be-9200d53b122e.PNG)

![newt 3](https://user-images.githubusercontent.com/42494104/52641747-d94d1800-2ed9-11e9-8bbf-2c9bf2b400a4.PNG)

I waited for an hour (i'm new to on-board dev)

I uninstalled and reinstalled newt and the gcc tool, tried to flash the hex file with nrfjprog cmd lines and read the output with PuTTY but it didn't work out.

I really don't see how to get away with this one.

regards
Vilucas

**Comment by pkettle** [comment]
Hi Vilucas, 
Did you erase the default flash that ships with the MDEK?

`
JLinkExe -device nRF52 -speed 4000 -if SWD

J-Link>erase
....

J-Link>exit
`

**Comment by Vilucas** [comment]
Hi again,

I was erasing only with nrfjprog, my bad.

It's now working, but when I load on the board and use the ' telnet localhost 19021'  I don't get the expected output 

![newt4](https://user-images.githubusercontent.com/42494104/52718807-9441e800-2fa4-11e9-85a7-50501f78a055.PNG)

**Comment by pkettle** [comment]
Hi Vilucas, 
You need to run `telnet localhost 19021` in a separate console while newt is still running. You should perhaps have a look at the Mynewt tutorials on same.

**Comment by Vilucas** [comment]
I did run the command on a fresh console just after running the target on the board. same issue, i don't have the expected output. My boards aren't on the same PC. I guess it's a dumb thing, but i can't find it.

Also, I tried the basic Blinky example with version 1.5.1 and 1.4.1 of newt on a  nRF840 and a dwm-1001 board. All work pretty well until I type the `newt load  nrf52_blinky` cmd. It doesn't print any error message, but the led doesn't blink. 

I will try on a Linux ...

**Comment by pkettle** [comment]
Hi Vilucas, 
I see the problem it looks like the default configuration was changed from RTT to UART. 

In ./twr_tag_tdma/syscfg.yml
Change:
```
CONSOLE_UART: 0
CONSOLE_RTT: 1
```

**Comment by Vilucas** [comment]
It's working well thanks. I'm looking to implement the measurement of the distance between nodes and tag on one of the apps.

I guess I should call the `slot_complete_cb()` fct with proper arguments in the main ? 

thx again for ur patience.

**Comment by pkettle** [comment]
Hi Vilucas,
Have a look at the twr_node_tdma/twr_tag_tdma pair; these provide the range measurement you seek. You do not call slot_comnplete_cb() this is a callback that is called by the MAC-Layer. You can use the slot_complete_cb() as a template for your application; currently, it just prints out a JSON string.

**Comment by Vilucas** [comment]
Hi again Paul,

I thought my issue was solved and I was wrong, I tried lots of things before coming back.

So I'm trying to have the range between the two devices and I thought I succeeded then I saw the output I got wasn't the output expected in the README 

this output is the one when I flash the bootloader on the two boards

![newt_2](https://user-images.githubusercontent.com/42494104/53031122-8096f580-346c-11e9-9de4-dfc2a84ea416.PNG)

otherwise if I don't and follow exactly the steps in the README of the twr_node_tdma app I get this output after typing the telnet cmd on a fresh console 

![newt_1](https://user-images.githubusercontent.com/42494104/53031218-b2a85780-346c-11e9-9b14-e8624e539747.PNG)

I don't have the ToF/range info.

If I put a printf in the while(1); loop, it prints my string 3 times then nothing.

-----------------------

this is my syscfg.yml file in the /d/mynewt-dw1000-apps/apps/twr_node_tdma/ directory

![newt_3](https://user-images.githubusercontent.com/42494104/53031341-f307d580-346c-11e9-90a9-f4966f29001e.PNG)

this is my syscfg.yml file in the  /d/mynewt-dw1000-apps/apps/twr_tag_tdma/ directory

![newt_4](https://user-images.githubusercontent.com/42494104/53031531-50038b80-346d-11e9-8ace-9368a3008db4.PNG)

I feel like the tag can't interact with the node.

Do you have any idea ?

regards

Vilucas

**Comment by pkettle** [comment]
Hi Vilucas, 
Are you trying to run both examples on the same physical machine? Newt does not support multiple targets as such only one board is getting port 19021.

**Comment by Vilucas** [comment]
I run them on two different machines, I connect the node to my main machine and run the tag on another PC, sometimes on an external batterie.

my newt and gcc : 

![version](https://user-images.githubusercontent.com/42494104/53078189-fa25f680-34f3-11e9-82ae-2a4daa1494a7.PNG)

I tried on two other boards, same situation. Also, I tried to connect the tag to the main machine and read his output  (can read the output only on the main machine so I have to choose which board i'm reading, I usually choose the node)
