### ISSUE TITLE
Compile error on Mac 

### ISSUE THREAD

**Issue by charuwalee** [Decawave/mynewt-dw1000-apps#9]
Hi,

I've tried to build the twr_tag_tdma application. Everything went well until step 6 when I type the command 

`newt run twr_tag_tdma 0` 

I got a compile error message as follows

<img width="1122" alt="Screen Shot 2562-03-13 at 13 59 27" src="https://user-images.githubusercontent.com/22586036/54260187-cf7f0900-459a-11e9-98da-38b6abdb6bdd.png">

and the build process stopped. 

I'm using Mac Mojave version 10.14.3.

Thank you in advance.
Charuwalee

**Comment by ftianf** [comment]
I have seen this on my ubuntu as well, you can either upgrade your tool chain (your one might have bug "https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119"), or suppress the warning by adding "-Wno-missing-braces" to ./repos/apache-mynewt-core/compiler/arm-none-eabi-m4/compiler.yml

**Comment by pkettle** [comment]
Hi Feng, 
Thanks for this.

**Comment by charuwalee** [comment]
Hello ftianf,

Thank so much for your help. It works now!!

Charuwalee
